language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
install:
- npm install -g firebase-tools
- npm install -g bower polymer-cli
- bower install
script: echo "Deploying!"
before_deploy: polymer build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --only hosting
